services:
  - type: web
    name: digital-coop-backend
    env: node
    plan: free
    buildCommand: cd backend-node && npm install
    startCommand: cd backend-node && npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /health
    region: oregon

  - type: web
    name: digital-coop-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
   
